---

- name: system update
  apt:
    upgrade: full
    update_cache: yes
    autoclean: yes
    autoremove: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: wireguard install
  apt:
    name: "wireguard"
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
